### ISSUE TITLE
Support for Swift 1.2

### ISSUE THREAD

**Issue by mogstad** [kylef/URITemplate.swift#11]
Swift 1.2 has been released in beta and URITemplate isn’t compatiable yet. As it’s not backward compatible and not officially released yet, I suggest creating a long running branch for it and merging it when 1.2 is released. I cloned it locally and it was rather streight forward to update—one line I’m not 100% sure about—if you create a branch for it I can PR into it.

**Comment by kylef** [comment]
Sure, I've created a branch `xcode-1.2` please feel free to make a pull request. If not, I will be adding support when I get chance.

**Comment by mogstad** [comment]
PRed: https://github.com/kylef/URITemplate.swift/pull/12
