### ISSUE TITLE
Create a release containing Package.swift

### ISSUE THREAD

**Issue by czechboy0** [kylef/URITemplate.swift#22]
Currently Package.swift is in master, but no release/tag is available, so it can't be pulled with swiftpm (AFAI tried).

(Edit: Just noticed you're importing Foundation, so I'm assuming we're waiting for Swift Foundation to make this available on all Swift platforms?)

**Comment by kylef** [comment]
Yes, this heavily uses regex and therefore wouldn't work on Linux until Foundation has regular expressions (if it doesn't already).

I also have a branch [no-regex](https://github.com/kylef/URITemplate.swift/tree/no-regex) which removes the uses of regex for variable expansion, but it still needs regex for variable extraction.

**Comment by czechboy0** [comment]
I just looked it up and it *might* technically already work: https://github.com/apple/swift-corelibs-foundation/blob/master/Foundation/NSRegularExpression.swift

**Comment by czechboy0** [comment]
But, there's no Package.swift, so I'm not sure what the easiest way to pull it in is anyway.

**Comment by czechboy0** [comment]
Sorry, I'm being stupid. This Foundation is going to be distributed with Swift binaries.

**Comment by kylef** [comment]
1.3.1 has been tagged.
