### ISSUE TITLE
Swift 2.3 Support

### ISSUE THREAD

**Issue by tolkiana** [kylef/URITemplate.swift#29]
Any plans to support Swift 2.3? 
I ran the convert tool because I need it for one of my projects, it's on my [fork](https://github.com/tolkiana/URITemplate.swift/tree/swift-2.3), is that something you would like to have in a branch here?

Also how should I run the test? I noticed it doesn't have a bridging header, is that expected?

**Comment by kylef** [comment]
URITemplate 1.3.1 should work in Swift 2.3. Is there any particular issue you're having? The source code should be compatible.

**Comment by davidwadden** [comment]
I'm seeing something similar when I attempt to import via Carthage in XCode 8.  I Tested the [fork](https://github.com/tolkiana/URITemplate.swift/tree/swift-2.3) above and that seemed to do the trick. 

```
A shell task (/usr/bin/xcrun xcodebuild -project /path/to/project/Carthage/Checkouts/URITemplate.swift/URITemplate.xcodeproj -scheme URITemplate -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** CLEAN FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
```

**Comment by tolkiana** [comment]
I'm integrating through cocoapods and I was trying to convert my project to Swift 2.3, the converter tool was showing URITemplate on the list of targets to convert.

I just pulled version 1.3.1 in a test project but seems to do the same.

`pod 'URITemplate', '~>1.3.1'`

![screen shot 2016-09-18 at 10 11 10 pm](https://cloud.githubusercontent.com/assets/5129887/18621206/ecab2706-7ded-11e6-8d41-640bad70a404.png)

Am I using a wrong version?

I saw you merged Swift 3.0 but unfortunately for my project I can not use Swift 3.0 yet.

For the question about the tests I just wanted to run them and make sure nothing was broken with the conversion.

**Comment by kylef** [comment]
@tolkiana 1.3.1 is the correct version. You can uncheck it from the migration converter. You will need to run `pod install` after you've migrated your user project to 2.3 because CocoaPods will introspect the `SWIFT_VERSION` flag and set it in the `Pods.xcodeproj`.

**NOTE**: *You will need a CocoaPods 1.1.0 pre-release so that `SWIFT_VERSION` will be set correctly in the Pods project.*

```shell
$ gem install cocoapods --pre
$ pod --version
1.1.0.rc.2
```

I think the reason Xcode selected it to be migrated is because the `Pods.xcodeproj` was generated by CocoaPods without a `SWIFT_VERSION`. This is because you ran `pod install` before migrating your project hence it didn't have a `SWIFT_VERSION`. This is expected.

**Comment by tolkiana** [comment]
Yeah, that worked for me, thanks!

**Comment by davidwadden** [comment]
It looks like Carthage hasn't implemented the feature to support `SWIFT_VERSION`  (https://github.com/Carthage/Carthage/issues/1445), so we still need that set in the `.xcodeproj` (such as https://github.com/tolkiana/URITemplate.swift/commit/8185e10c66c7f5ce0e2140ba2f9b9cee0fbb7df2).

I've seen a common convention amongst Swift frameworks to publish a topic branch `swift-2.3`.  Will you create one for us Carthage users so we don't have to track a fork?

**Comment by kylef** [comment]
I've made stable branch from the 1.x version to add Swift 2.3 support and made a 1.4.0 release.

So, here are the past three releases and which Swift version they can be used with:

- [URITemplate 1.3.1](https://github.com/kylef/URITemplate.swift/releases/tag/1.3.1) - Swift 2.2
- [URITemplate 1.4.0](https://github.com/kylef/URITemplate.swift/releases/tag/1.4.0) - Swift 2.3
- [URITemplate 2.0.0](https://github.com/kylef/URITemplate.swift/releases/tag/2.0.0) - Swift 3.0
