### ISSUE TITLE
URITemplate 2.0.0 Dependency

### ISSUE THREAD

**Issue by cosminstirbu** [kylef/URITemplate.swift#31]
Hi,

There is a Swift 3.0 version of URITemplate.
Can we please update the subspec to this version?

https://github.com/kylef/URITemplate.swift/blob/master/URITemplate.podspec

Thanks,
Cosmin

**Comment by kylef** [comment]
I'm not sure i follow @cosminstirbu. The URITemplate 2.0 release supports Swift 3.0. The pod spec you linked to has already been updated and the version is already URITemplate 2.0.

**Comment by cosminstirbu** [comment]
I logged this issue on the wrong project. I meant to log it on https://github.com/kylef/Mockingjay/issues?q=is%3Aopen+is%3Aissue.

Sorry about that.

**Comment by kylef** [comment]
@cosminstirbu there is a branch that's nearly ready with Swift 3 support in Mockingjay: https://github.com/kylef/Mockingjay/pull/63

**Comment by cosminstirbu** [comment]
Great. We'll point to that branch until a new version is released via Cocoapods.

Thank you.
