### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by klaaspieter** [kylef/URITemplate.swift#33]
Before 8cf2b3cf5612cde716af7225aa04da6f0c45fe7d was implicitly supported through the Xcode project. With the Xcode project removed, Carthage can no longer install URITemplate. 

Are you willing to consider a PR that re-adds Carthage support? I can imagine you don't want to maintain a Xcode project for this purpose but perhaps we can use `swift package generate-xcodeproj` creatively.

**Comment by kylef** [comment]
> I can imagine you don't want to maintain a Xcode project

I'd rather not add an have to manage specific files for IDEs.

> but perhaps we can use swift package generate-xcodeproj creatively.

Yes, you can use swift package generation, check out:

https://fuller.li/posts/using-swift-package-manager-with-carthage/
