### ISSUE TITLE
Swift 5 compatibility

### ISSUE THREAD

**Issue by kudzaiTnexus** [kylef/URITemplate.swift#47]
Projects that make use of this pod aren't able to upgrade to swift 5 because URITemplate isn't swift 5 compatible.

**Comment by JeneaVranceanu** [comment]
+1

**Comment by romainbiard** [comment]
Please guys do you need help to achieve this ? (a PR seems to be open with a swift 5 compatible code)

**Comment by ppamorim** [comment]
Please fix this, I cannot run my unit tests.

**Comment by kylef** [comment]
https://github.com/kylef/URITemplate.swift/releases/tag/3.0.0
