### ISSUE TITLE
s.swift_version = '5.0'

### ISSUE THREAD

**Issue by SentulAsia** [kylef/URITemplate.swift#50]
I got this error when installing:
```
[!] Failed to load 'URITemplate' podspec:
[!] Invalid `URITemplate.podspec` file: undefined method `swift_versions=' for #<Pod::Specification name="URITemplate">
Did you mean?  swift_version=
               swift_version.
```

**Comment by kylef** [comment]
@SentulAsia I think the CocoaPods you are using us outdated, can you try again with cocoapods 1.7.x which adds support for swift versions?

**Comment by SentulAsia** [comment]
@kylef I can’t change my cocoapods version until september... I guess I’ll stay to swift 4.2 then...

**Comment by SentulAsia** [comment]
@kylef can you do this?, if yes, I'll submit a PR:
```
if spec.respond_to?(:swift_versions) then
    spec.swift_versions = ["4.2", "5.0"]
  else
    spec.swift_version = "5.0"
  end
```

**Comment by kylef** [comment]
@SentulAsia That won't work because the specification will be converted by CocoaPods into JSON upon submission. You can make a copy of a podspec in Ruby and keep it in your project and reference it internally as a workaround.

**Comment by SentulAsia** [comment]
@kylef Thanks for the follow up, already updated to latest version and that solved the issue. Thanks for the reminder.
