### ISSUE TITLE
Invalid Exclude '…/Sources/Spectre/XCTest@4.swift': File not found 

### ISSUE THREAD

**Issue by Gharib-sara** [kylef/URITemplate.swift#53]
Hi,

I'm getting this warning on Xcode 13

`Invalid Exclude '.../SourcePackages/checkouts/Spectre/Sources/Spectre/XCTest@4.swift': File not found.`
 
It appears that Spectre released [a fix](https://github.com/kylef/Spectre/pull/48) for this issue - Could you please get the URITemplate updated with that fix?

**Comment by Gharib-sara** [comment]
@kylef I can see you already update Spectre version, could you please create a new release for this package?

**Comment by kylef** [comment]
This is released under 6affd42 or 3.0.1.
